using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibHIRT.Grunt.Models.HaloInfinite
{
    public enum ItemType
    {
        All,
        ArmorChestAttachment,
        ArmorCoating,
        ArmorGlove,
        ArmorHelmetAttachment,
        ArmorHelmet,
        ArmorKneePad,
        ArmorTheme,
        ArmorLeftShoulderPad,
        ArmorRightShoulderPad,
        ArmorHipAttachment,
        ArmorWristAttachment,
        ArmorVisor,
        ArmorEmblem,
        ArmorFx,
        ArmorMythicFx,
        ArmorCore,
        SpartanActionPose,
        SpartanStance,
        SpartanBackdropImage,
        SpartanEmblem,
        WeaponCharm,
        WeaponAmmoCounterColor,
        WeaponCoating,
        WeaponDeathFx,
        WeaponEmblem,
        WeaponTheme,
        WeaponStatTracker,
        WeaponCore,
        WeaponAlternateGeometryRegion,
        AiColor,
        AiModel,
        AiTheme,
        AiCore,
        VehicleAlternateGeometryRegion,
        VehicleCharm,
        VehicleCoating,
        VehicleEmblem,
        VehicleFx,
        VehicleHorn,
        VehicleTheme,
        VehicleCore,
        SpartanVoice
    }
    public enum ItemTypeList
    {
        ArmorChestAttachmentsOwnableCount,
        ArmorCoatingsOwnableCount,
        ArmorGlovesOwnableCount,
        ArmorHelmetAttachmentsOwnableCount,
        ArmorHelmetsOwnableCount,
        ArmorKneePadsOwnableCount,
        ArmorThemesOwnableCount,
        ArmorLeftShoulderPadsOwnableCount,
        ArmorRightShoulderPadsOwnableCount,
        ArmorHipAttachmentsOwnableCount,
        ArmorWristAttachmentsOwnableCount,
        ArmorVisorsOwnableCount,
        ArmorEmblemsOwnableCount,
        ArmorFxsOwnableCount,
        ArmorMythicFxsOwnableCount,
        ArmorCoresOwnableCount,
        SpartanActionPosesOwnableCount,
        SpartanStancesOwnableCount,
        SpartanBackdropImagesOwnableCount,
        SpartanEmblemsOwnableCount,
        WeaponCharmsOwnableCount,
        WeaponAmmoCounterColorsOwnableCount,
        WeaponCoatingsOwnableCount,
        WeaponDeathFxsOwnableCount,
        WeaponEmblemsOwnableCount,
        WeaponThemesOwnableCount,
        WeaponStatTrackersOwnableCount,
        WeaponCoresOwnableCount,
        WeaponAlternateGeometryRegionsOwnableCount,
        AiColorsOwnableCount,
        AiModelsOwnableCount,
        AiThemesOwnableCount,
        AiCoresOwnableCount,
        VehicleAlternateGeometryRegionsOwnableCount,
        VehicleCharmsOwnableCount,
        VehicleCoatingsOwnableCount,
        VehicleEmblemsOwnableCount,
        VehicleFxsOwnableCount,
        VehicleHornsOwnableCount,
        VehicleThemesOwnableCount,
        VehicleCoresOwnableCount,
        SpartanVoicesOwnableCount

    }

}
