<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <StartupObject>HaloInfiniteResearchTools.EntryPoint</StartupObject>
    <ApplicationIcon>IconHIRT.ico</ApplicationIcon>
    <PackageIcon>download.jpeg</PackageIcon>
    <PackageProjectUrl>https://github.com/urium1186/HIRT</PackageProjectUrl>
    <RepositoryUrl>https://github.com/urium1186/HIRT.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icon\cup-border.png" />
    <None Remove="Resources\Icon\IconHIRT.ico" />
    <None Remove="Resources\Icon\icons8-add-image-40.png" />
    <None Remove="Resources\Icon\icons8-close-40.png" />
    <None Remove="Resources\Icon\icons8-downloading-updates-40.png" />
    <None Remove="Resources\Icon\icons8-eye-40.png" />
    <None Remove="Resources\Icon\icons8-paper-plane-40.png" />
    <None Remove="Resources\Icon\icons8-refresh-40.png" />
    <None Remove="Resources\Icon\icons8-save-40.png" />
    <None Remove="Resources\Icon\icons8-screenshot-40.png" />
    <None Remove="Resources\Icon\icons8-upward-arrow-40.png" />
    <None Remove="Resources\Icon\icons8-waste-40.png" />
    <None Remove="Resources\Icon\icons8-youtube-logo-48.png" />
    <None Remove="Resources\Icon\icons8-youtube-squared-240.png" />
    <None Remove="Resources\Icon\icons8-youtube-squared-48.png" />
    <None Remove="Resources\Icon\paypal.png" />
    <None Remove="Resources\Icon\screen-shot-00.jpeg" />
    <None Remove="Resources\images\item_loading.jpeg" />
    <None Remove="Resources\images\login_bg.jpeg" />
    <None Remove="Resources\images\login_bg_0.jpeg" />
    <None Remove="Resources\images\login_bg_1.jpeg" />
    <None Remove="Resources\images\OIG1_1.jpeg" />
    <None Remove="Resources\images\OIG1_8.jpeg" />
    <None Remove="Resources\images\OIG1_9.jpeg" />
    <None Remove="Resources\images\OIG2_1.jpeg" />
    <None Remove="Resources\images\OIG2_2.jpeg" />
    <None Remove="Resources\images\OIG2_4.jpeg" />
    <None Remove="Resources\images\online_custom_banner.jpeg" />
    <None Remove="Resources\images\paypal.jpg" />
    <None Remove="Resources\images\spinner\spinner_adv1_ru_0.png" />
    <None Remove="Resources\images\spinner\spinner_adv1_ru_1.png" />
    <None Remove="Resources\images\spinner\spinner_adv1_ru_2.png" />
    <None Remove="Resources\images\spinner\spinner_adv1_ru_border.png" />
    <None Remove="Resources\images\spinner\spinner_adv1_ru_border_circular.png" />
    <None Remove="Resources\images\unnamed.jpg" />
    <None Remove="Resources\xml_tags\xml_tags.zip" />
    <None Remove="Views\unnamed.jpg" />
    <None Remove="Views\WhatsApp Image 2023-07-10 at 11.56.57.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="IconHIRT.ico" />
    <Content Include="Resources\Icon\cup-border.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\IconHIRT.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-add-image-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-close-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-downloading-updates-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-eye-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-paper-plane-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-refresh-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-save-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-screenshot-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-upward-arrow-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-waste-40.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-youtube-logo-48.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-youtube-squared-240.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\icons8-youtube-squared-48.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\paypal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icon\screen-shot-00.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\item_loading.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\login_bg.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\login_bg_0.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\login_bg_1.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\OIG1_1.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\OIG1_8.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\OIG1_9.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\OIG2_1.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\OIG2_2.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\OIG2_4.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\online_custom_banner.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\paypal.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\spinner\spinner_adv1_ru_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\spinner\spinner_adv1_ru_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\spinner\spinner_adv1_ru_2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\spinner\spinner_adv1_ru_border.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\spinner\spinner_adv1_ru_border_circular.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\unnamed.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\xml_tags\xml_tags.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
	  <Content Include="Resources\images\Clear_filters.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_bipd.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_char.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_file.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_hlmt.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_levl.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_mode.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_module.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_ocgd.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_sbsp.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_weap.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\images\open_vehicle.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DirectXTexNet" Version="1.0.3">
      
    </PackageReference>
    <PackageReference Include="Microsoft.Direct3D.DXC" Version="1.7.2308.12" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
    <PackageReference Include="ScreenCapture.NET" Version="2.0.4" />
	  <PackageReference Include="System.CommandLine" Version="2.0.0-beta3.22114.1" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.5.0" />
    <PackageReference Include="Javi.ExplorerTreeView" Version="1.0.4" />
    <PackageReference Include="JSONTreeView" Version="1.1.0" />
    <PackageReference Include="LiveSearchTextBoxControl" Version="0.1.1" />
	  <PackageReference Include="AvalonEdit" Version="6.1.3.50" />
	  <PackageReference Include="DeepCopy.Fody" Version="1.0.16" />
	  <PackageReference Include="Fody" Version="6.6.3">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="HelixToolkit.SharpDX.Assimp" Version="2.21.1" />
	  <PackageReference Include="HelixToolkit.SharpDX.Core.Wpf" Version="2.21.1" />
	  <PackageReference Include="Magick.NET-Q16-HDRI-AnyCPU" Version="11.2.1" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
	  <PackageReference Include="Microsoft.Identity.Client" Version="4.55.0" />
	  <PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.55.0" />
	  <PackageReference Include="Microsoft.Identity.Client.Desktop" Version="4.55.0" />
	  <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.2" />
	  <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
	  <PackageReference Include="PropertyChanged.Fody" Version="3.4.1" />
	  <PackageReference Include="WPFHexaEditor" Version="2.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AppSettings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppSettings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="AppSettings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>AppSettings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\db\database.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Icon\Logo-Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\Clear_filters.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1_2.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1_3.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1_4.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1_5.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1_6.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1_7.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1_(8).jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG1.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG2_3.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG2_5.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG2_6.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG2_7.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG2_8.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG2_9.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG2.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\OIG3.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_bipd.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_char.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_file.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_hlmt.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_levl.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_mode.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_mode_.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_module.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_ocgd.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_ocgd_2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_sbsp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_vehicle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\images\open_weap.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\dxc\dxc.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\dxc\dxcompiler.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\dxc\dxil.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Icon\0x-Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Icon\Close-Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Icon\Open-File-Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Icon\Save-Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\dxil-spirv\dxil-extract.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\dxil-spirv\dxil-spirv-c-shared.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\dxil-spirv\dxil-spirv.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\spirv-cross\spirv-cross-c-shared.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\shaders\spirv-cross\spirv-cross.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\xboxservice\client.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\xboxservice\tokens.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibHIRT\LibHIRT.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Processes\Utils\" />
    <Folder Include="Resources\shaders\dxc\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Jorge\Downloads\download.jpeg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
